import { Injectable } from '@angular/core';
import { IQuestionAnswer } from './question-answer';

@Injectable()
export class QuestionsDataService {
    getQuestionAnswer(): IQuestionAnswer[] {
        return [
            {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Cannot start with a number, cannot have spaces, reserved words nor characters except \"$\" \"_\", the variable...",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "name",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            },
            {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Prints a console  a warning",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "console.warn();",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            },
            {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Prints a console error",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "console.error();",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            },
            {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Data types that represent a single value, meaning it is not an object.",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Primitive",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "Write the name of the data type",
                "errorMessage": "Wrong answer"
            },
            {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Mention the Primitive Data Types alphabetically ordered",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Boolean, Null, Number, String, Symbol, Undefined",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Tip, there are 6"
            },
            {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "A special function syntactically differently that generally takes two",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Operator",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            },
            {
                "subject": "JS",
                "questionTopic": "Math Functions",
                "class": "bdg4",
                "questionPart1": "Write the code to print in the console a Random Number",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "console.log(Math.random());",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            },
            {
                "subject": "JS",
                "questionTopic": "Math Functions",
                "class": "bdg4",
                "questionPart1": "Write the code to Round and print in the console this number: 8.5",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "console.log(Math.round(8.5));",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            },
            {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Mention 7 Host Objects alphabetically ordered",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Comment, Console, Document, Element, Event, Node, Window",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Tip: C, C, D, E, E, N, W"
            },
            {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Mention 7 Core Objects alphabetically ordered",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Array, Boolean, Date, Math, Number, Object, String",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Tip: A, B, D, M, N, O, S"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Switch Statement",
                "questionPart2": "Create the var \"varCompare\" = 10. Then write the code to compare through a Switch statement the var \"varCompare\" against 2 values to print in the console:",
                "questionPart3": "-\"Option1\" if equals to 5.",
                "questionPart4": "-Or printing \"Option2\" if equals to 9.",
                "questionPart5": "-Or a third option as default, printing in the console \"Option3\".",
                "answer": "var varCompare = 10; \nswitch (varCompare) { \ncase 5: \nconsole.log(\"Option1\"); \nbreak; \ncase 9: \nconsole.log(\"Option2\"); \nbreak; \ndefault: \nconsole.log(\"Option3\"); \nbreak; \n}",
                "id": "",
                "rows": 12,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer."
            },
            {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Write the code to convert \"myVar\" into a number",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Number(myVar);",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Host Objects, Core Objects and Objects defined by the coder are types of what",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Javascript Objects",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "Javascript _________",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "All the coding written by the developer is by default child of the Window Object",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "True",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "True or false",
                "errorMessage": "True or false"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Is it possibe to redeclare one of the methods that are by default methods of the Window? Like redefining the alert() so it logs a console message instead of alerting?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Yes",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "Yes or no",
                "errorMessage": "True or false"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Strict mode makes it easier to write \"secure\" JavaScript.\nStrict mode changes previously accepted \"bad syntax\" into real errors.\nIn normal JavaScript, mistyping a variable name creates a new global variable. In strict mode, this will throw an error, making it impossible to accidentally create a global variable.\nIn normal JavaScript, a developer will not receive any error feedback assigning values to non-writable properties.\In strict mode, any assignment to a non-writable property, a getter-only property, a non-existing property, a non-existing variable, or a non-existing object, will throw an error.",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "True",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "True or false",
                "errorMessage": "True or false"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "What is the name of declaring a property or method using square brackets",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Computed member access",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Square brakets notation or Computed member access is a way that we can use to write \"invalid identifiers\" not allowed in a different way. In addition we could use variables. True or False?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "True",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "True or false",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Write the code to encapsulate an anonymus function in to make it an IIFE?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "(function(){}(););",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Naming the same 2 different variables in 2 different scopes so making them to keep their value and not to overwrite themselves, what is the term to refer to that?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Shadowing",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "In a for loop when it ends, after latest validation, does the counter still sum ++ one last time?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Yes",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "What is the name of the program that converts the code we write into a set of computer instructions that the computer understands and verifies our grammar?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Syntax Parser",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "What is the name we use to define where an element is written and what sorrunds it?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Lexical Environment",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "What is the name we use to define a wrapper to help manage the code that is running?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Execution context",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "In JavaScript, how do we call a collection of key-value pairs?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Object",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Mention separated by commas what the Javascript Engine creates first when loads our code",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Global object, variable \"this\"",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Running a function (by using parenthesis), what is the term to refer to it",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Invocation",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Operator that first tries to coherce the values and then it compares them",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "==",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "JS",
                "questionTopic": "Basics",
                "class": "bdg4",
                "questionPart1": "Operator that compares strictly the values with no coercion.",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "===",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, /*{
                "subject": "StoryLine",
                "questionTopic": "Basics",
                "class": "bdg6",
                "questionPart1": "Where is the best place for troubleshooting?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Story view panel and triggers panel",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer, do not forget the PANEL word"
            }, {
                "subject": "StoryLine",
                "questionTopic": "Basics",
                "class": "bdg6",
                "questionPart1": "What are the three main authoring components?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "States panel, Slide Layers Panel and Triggers Panel",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer, do not forget the PANEL word"
            }, {
                "subject": "StoryLine",
                "questionTopic": "Basics",
                "class": "bdg6",
                "questionPart1": "What is the extension of editable StoryLine projects",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": ".story",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "StoryLine",
                "questionTopic": "Basics",
                "class": "bdg6",
                "questionPart1": "How do you create a Quiz?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "By adding a new slide and selecting quiz",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "By adding a ___ _____ and _________ ____",
                "errorMessage": "By adding a ___ _____ and _________ ____"
            }, {
                "subject": "StoryLine",
                "questionTopic": "Basics",
                "class": "bdg6",
                "questionPart1": "When creating a question of a quiz, what layout options do we have available by default?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Form View and Slide View",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "____ ____ and _____ ____",
                "errorMessage": "____ ____ and _____ ____"
            }, {
                "subject": "StoryLine",
                "questionTopic": "Basics",
                "class": "bdg6",
                "questionPart1": "When you create a quiz, how do you prevent the questions to display in a random order?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "In the question tab by changing the shuffle option",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "In the ________ tab by changing the _______ option",
                "errorMessage": "In the ________ tab by changing the _______ option"
            }, {
                "subject": "StoryLine",
                "questionTopic": "Basics",
                "class": "bdg6",
                "questionPart1": "Ho do you create a quiz question from a regular slide?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "By clicking on Insert tab and then Convert to Freeform",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "By clicking on ______ tab and then Convert to ________",
                "errorMessage": "By clicking on ______ tab and then Convert to ________"
            }, {
                "subject": "StoryLine",
                "questionTopic": "Basics",
                "class": "bdg6",
                "questionPart1": "If you want to change the template of the questions feedback that displays after responding a question for it to contain the logo, etc. Where do you change the master?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "By editing the Feedback Master in View tab",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "By editing the ________ Master in ____ tab",
                "errorMessage": "By editing the ________ Master in ____ tab"
            }, {
                "subject": "StoryLine",
                "questionTopic": "Basics",
                "class": "bdg6",
                "questionPart1": "Hod do you create a quiz results slide (to display the result of several questions)?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "In the Story View panel first select the scene that contains the questions, then in the\nInsert tab click on New Slide. The Insert Slides window will pop up, from there select \nQuizzing tab and then select Graded Result slide",
                "id": "",
                "rows": 3,
                "type": "",
                "contentType": "",
                "placeholder": "In the _____ ____ panel first select the scene that contains the questions, then in the ______ tab click on New Slide. The Insert Slides window will pop up, from there select ________ tab and then select ______ ______ slide",
                "errorMessage": "In the _____ ____ panel first select the scene that contains the questions, then in the ______ tab click on New Slide. The Insert Slides window will pop up, from there select ________ tab and then select ______ ______ slide"
            }, {
                "subject": "StoryLine",
                "questionTopic": "Basics",
                "class": "bdg6",
                "questionPart1": "What is the path to get to the tracking publishing options for LMS?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "File>Publish>LMS>Reporting and Tracking>Tracking",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "____ > _______ > ___ > _________ and ________ > ________",
                "errorMessage": "____ > _______ > ___ > _________ and ________ > ________"
            }, {
                "subject": "StoryLine",
                "questionTopic": "Basics",
                "class": "bdg6",
                "questionPart1": "What are the tracking options when we publish for LMS?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Track using number of slides viewed or using quiz result",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "Track using ______ of ______ ______ or using ____ ______",
                "errorMessage": "Track using ______ of ______ ______ or using ____ ______"
            },{
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "What are the techniques to develop an User Centered Design",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Analyzing User Data, Ideation Techniques, Senarios and StoryBoards, Paper Prototyping, Implementation Planning",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "A________ U___ D___, I_______ T_________, S_______ and S__________, P____ P__________, I_____________ P_______",
                "errorMessage": "A________ U___ D___, I_______ T_________, S_______ and S__________, P____ P__________, I_____________ P_______"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "We should not jump into coding the app and then just force the devices to run on it, we must decide what device suits best for the needs the user has, this is the definition of...",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "MultiDevice Design",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "When the user can perform actions sit and has a table, when information will be exposed at double click or doing hover, for tasks that will require too much writing.",
                "questionPart2": "Tese are the characteristics of an application for what device?",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "PC",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "Are used the 75% of times being at home, mostly in the couch and bed, reading books, games and consuming content are excellent tasks for these devices. Large enough to interact with and view information with no need to leave the relaxed position",
                "questionPart2": "Tese are the characteristics of an application for what device?",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Tablet",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "Can be used anywhere, specially on the go, user of a laser scanner will use the mobile in the store, but most important, people use their phones even while doing another activities, like watching TV, in the desk while working on a PC, the use of the app will depend more in what the app does.",
                "questionPart2": "Tese are the characteristics of an application for what device?",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Mobile",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "Who + What + When + Where",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "User Context",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "Best design approach:",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Design for the users context, not the device",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "Cost and time saving, one version of code that will work everywhere, open platform, created on any software and accessible from any browser, future proof, no matter the Operating System, the WebApp will always work in future releases.",
                "questionPart2": "The above are some of the benefits of?",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Web App",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "Cost and Time investment, high maintenance effort, having to find and install the app, content restrictions and required approvals on the market places, fees on sales to market places owners.",
                "questionPart2": "The above are some of the disadvantages of?",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Native Apps",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "Faster Performance. Once the App is installed, the device will download only data when required, the interface is already there,the App works offline, better visual design and animation control, use full range of gestures, all device hardware capabilities are available to be used.",
                "questionPart2": "The above are some of the benefits of?",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Native Apps",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "Slow performance, no offline functionality, limited to browser-capable gestures.",
                "questionPart2": "The above are some of the disadvantages of?",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Web App",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "Save on costs by reusing code, take advantage of device Operating System and Hardware capabilities, app listed in the market place, slower performance when it loads from web.",
                "questionPart2": "The above are the considerations for?",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Hybrid Apps",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "What is the safe zone for elements for touch devices?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "7mm",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "From 40px to 50px",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "Review the problem statement and research as a team. On your own sketch your product solution ideas using whichever technique works for you.	As a team evaluate the ideas and keep the ones that bring more value. Work in pairs to synthetize the good concepts and come up with next better design concept. Finally, together as a group again. critique the solution and keep the good ones and create prototypes.",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Design Charrete",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "The team members bring 2 examples of existent products that may after mixed present a functionality that could resolve the problems, we are not copying, we are getting inspiration.",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Possible Futures",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "Is a low fidelity static representation of a design. It should show the main groups of content (what?), the structure of information (where?) and visualization of the user interaction (how?)",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Wireframe",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "It is an static representation of the design, it could be very high fidelity, very often it is a screenshot of the final design.",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "MockUp",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "User testing reusable backbone of the interface, the main porpuse of it is the interactivity, it could be low fidelity to very high fidelity. Can be made in paper or software.",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Prototype",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "UI",
                "questionTopic": "Basics",
                "class": "bdg3",
                "questionPart1": "Describe user and product behavior in detail. Provide an understanding of design viability. Cover end-to-en detail on interaction. Serve as a great communication tool. Predicting user behavior. Uncovering error conditions. Preventing rework",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Scenarios and Storyboards benefits",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            },{
                "subject": "SQL",
                "questionTopic": "Basics",
                "class": "bdg1",
                "questionPart1": "Run a query that returns 3 records from the table \"tableCustomers\" that have completed the course #5 (in column completedCourses), and it is ordered ascending by the memeber member_id",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "SELECT TOP 3 * FROM tableCustomers WHERE completedCourses = '05' ORDER BY member_id ASC;",
                "id": "",
                "rows": 5,
                "type": "",
                "contentType": "",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "Ionic",
                "questionTopic": "Basics",
                "class": "bdg2",
                "questionPart1": "As the forst step to work with Ionic, what is the NPM command to install Ionic2?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "npm install -g ionic cordova",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "Ionic",
                "questionTopic": "Basics",
                "class": "bdg2",
                "questionPart1": "What is the NPM command to start a new Ionic2 project with TypeScript? (Name the project \"projectName\")",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "ionic start projectName tabs --v2  --ts",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "Ionic",
                "questionTopic": "Basics",
                "class": "bdg2",
                "questionPart1": "What is the command to run the Ionic application on the browser?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "ionic serve",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "Ionic",
                "questionTopic": "Basics",
                "class": "bdg2",
                "questionPart1": "What is the command to run your app in a device?",
                "questionPart2": "Replace the device OS name by [device]",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "ionic run [device]",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "_____ ___ [device]",
                "errorMessage": "_____ ___ [device]"
            }, {
                "subject": "Ionic",
                "questionTopic": "Basics",
                "class": "bdg2",
                "questionPart1": "For running in a device, first you need to install a platform for Cordova, what is the command? For this especific example use the version 5.1.1",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "cordova platform add android@5.1.1",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "_______ ________ ___ _______@5.1.1",
                "errorMessage": "_______ ________ ___ _______@5.1.1"
            },*/ {
                "subject": "AngularJS",
                "questionTopic": "Basics",
                "class": "bdg10",
                "questionPart1": "What is a controller?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Is the central player in the application. Contains logic and State. Its primary responsibility is to create a scope object.",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Basics",
                "class": "bdg10",
                "questionPart1": "For an application named \"myApp\", create the main controller named \"MainController\"",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "myApp.controller(\"MainController\", function MainController($scope) {…}",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Basics",
                "class": "bdg10",
                "questionPart1": "What is the scope?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Is the way the Controller communicates with the view. It is used to expose the model to the view but it is not the model.",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Basics",
                "class": "bdg10",
                "questionPart1": "What is the model",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "The model is the data that is out into the scope.",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Basics",
                "class": "bdg10",
                "questionPart1": "What is the view?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Made of bindings and directives. The communication with the user. The events on the view \ncan call methods in the scope.",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Basics",
                "class": "bdg10",
                "questionPart1": "Describe a Service",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Holds the complex business logic and the heavy processing of the application. It is also the piece of angular in charge of communicating with the server.",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Directives",
                "class": "bdg10",
                "questionPart1": "What is a directive?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "A way to implement new functionality to html elements",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Directives",
                "class": "bdg10",
                "questionPart1": "What types of directives are there?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Tag, attribute, class and comment",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Directives",
                "class": "bdg10",
                "questionPart1": "What does the NG Bind directive do?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Passes data to the View like the one way binding does, the only difference is that this time as an attribute",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            },{
                "subject": "AngularJS",
                "questionTopic": "Directives",
                "class": "bdg10",
                "questionPart1": "Write an example of NG Bind using as variable \"someVar\"",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "ng-bind=\"{{ someVar }}\"",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Directives",
                "class": "bdg10",
                "questionPart1": "What does the NG Bind Template directive do?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Passes data to the View but it can be more than 1 expression",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Directives",
                "class": "bdg10",
                "questionPart1": "Write an example of NG Bind TEmplate using as variables \"someVar\" and \"someVar2\"",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "ng-bind-template=\"{{ someVar1 someVar2 }}\"",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            },{
                "subject": "AngularJS",
                "questionTopic": "Directives",
                "class": "bdg10",
                "questionPart1": "What does NG Cloak directive do?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Hides the html tag that contains the directive and waits for the angular code to be parsed before displaying content so we avoid displaying Angular code in the screen. In addition there is necessary to add some css rule to hide the element that contains the directive, usualy the body tag.",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Directives",
                "class": "bdg10",
                "questionPart1": "Write an example of NG Cloak directive in the body tag",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "<body ng-cloak>",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Directives",
                "class": "bdg10",
                "questionPart1": "What does ng Style directive do?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Passes the styles contained by a varibale (as an object) as inline styles.",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Directives",
                "class": "bdg10",
                "questionPart1": "Write the code to display the ngStyle directive in a div, the name of the variable is \"myStyles\"",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "<div ng-style=\"myStyles\">",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Directives",
                "class": "bdg10",
                "questionPart1": "What does ngDisabled directive do?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Disables an element based on wether or not the value of the directive returns true",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Directives",
                "class": "bdg10",
                "questionPart1": "Write an example of the ngDisabled directive id the variable \"myTrigger\" is true applied to a div",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "<div ng-disabled=\"myTrigger\">",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Directives",
                "class": "bdg10",
                "questionPart1": "Name 6 more directives",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "ngChecked, ngMultiple, ngReadonly, ngSelected, ngForm, ngSubmit, ngHref, ngSrc, ngNonBindable",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Directives",
                "class": "bdg10",
                "questionPart1": "Mention the 2 restrictions to use Angular JS with Internet Explorer",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Polyfill JSON.stringify. Never to use tag form directive",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "What does a Filter do?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Modifies the output, Gives format, Sorts Dataset, Filters Dataset",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "Using a Filter order by descending \"someVar\"",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "| orderBy:  someVar",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "Using a Filter limit by 2 \"someVar\"",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "| limitTo:  2",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "What does a Filter do?",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "Displays only the items that match the query. We can limit a filter to only search in a specific filed if in the ng-model we pass only the matched content in a property of the object passed: ng - model=\"someQuery.propertyOfMyObject\"",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            },{
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "Using a Filter filter \"someQuery\"",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "| filter: someQuery",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "Create a Custom Filter that from these numbers 1, 2 and 3 returns their name written with words",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "myApp.filter('someInput', function () {\n return function (someInput) {\n    switch (someInput) {\n        case 1:\n            return \"One\";\n        case 2:\n            return \"Two\";\n        case 3:\n            return \"Three\";\n    };\n  };\n});",
                "id": "",
                "rows": 13,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }/*, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }, {
                "subject": "AngularJS",
                "questionTopic": "Filters",
                "class": "bdg10",
                "questionPart1": "",
                "questionPart2": "",
                "questionPart3": "",
                "questionPart4": "",
                "questionPart5": "",
                "answer": "",
                "id": "",
                "rows": 2,
                "type": "",
                "contentType": "code",
                "placeholder": "",
                "errorMessage": "Wrong answer"
            }*/
        ];
    }
}
